name: cudaenv
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - cuda-version=11.8
  - cudatoolkit=11.8.0
  - cudnn=9.8.0.87
  - expat=2.6.4
  - libffi=3.4.4
  - openssl=3.4.1
  - pip=25.0
  - python=3.12.9
  - setuptools=75.8.0
  - sqlite=3.45.3
  - tk=8.6.14
  - ucrt=10.0.22621.0
  - vc=14.42
  - vc14_runtime=14.42.34438
  - vs2015_runtime=14.42.34438
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.13
      - aiosignal==1.3.2
      - attrs==25.3.0
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - colorama==0.4.6
      - contourpy==1.3.1
      - cycler==0.12.1
      - fastmri==0.3.0
      - filelock==3.13.1
      - fonttools==4.56.0
      - frozenlist==1.5.0
      - fsspec==2024.6.1
      - h5py==3.13.0
      - idna==3.10
      - imageio==2.37.0
      - jinja2==3.1.4
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - lightning-utilities==0.14.1
      - markupsafe==2.1.5
      - matplotlib==3.10.1
      - mpmath==1.3.0
      - multidict==6.1.0
      - networkx==3.3
      - numpy==2.1.2
      - packaging==24.2
      - pandas==2.2.3
      - pillow==11.0.0
      - propcache==0.3.0
      - pyparsing==3.2.1
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==2.5.0.post0
      - pytz==2025.1
      - pyyaml==6.0.2
      - requests==2.32.3
      - runstats==2.0.0
      - scikit-image==0.25.2
      - scipy==1.15.2
      - six==1.17.0
      - sympy==1.13.1
      - tifffile==2025.3.13
      - torch==2.6.0+cu118
      - torchaudio==2.6.0+cu118
      - torchmetrics==1.6.3
      - torchsummary==1.5.1
      - torchvision==0.21.0+cu118
      - tqdm==4.67.1
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - urllib3==2.3.0
      - yarl==1.18.3
