name: mri
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.12.31
  - expat=2.6.4
  - libcxx=14.0.6
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.15
  - pip=24.2
  - python=3.12.8
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiosignal==1.3.2
      - alembic==1.14.1
      - annotated-types==0.7.0
      - anyio==4.8.0
      - appnope==0.1.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - astunparse==1.6.3
      - async-lru==2.0.4
      - attrs==24.3.0
      - azure-common==1.1.28
      - azure-core==1.32.0
      - azure-identity==1.20.0
      - azure-mgmt-core==1.5.0
      - azure-storage-blob==12.19.0
      - azureml-dataprep==5.1.6
      - azureml-dataprep-native==41.0.0
      - azureml-dataprep-rslex==2.22.5
      - azureml-fsspec==1.3.1
      - azureml-mlflow==1.59.0.post1
      - babel==2.16.0
      - beautifulsoup4==4.12.3
      - bleach==6.2.0
      - blinker==1.9.0
      - cachetools==5.5.2
      - certifi==2024.12.14
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - click==8.1.8
      - cloudpickle==2.2.1
      - comm==0.2.2
      - contourpy==1.3.1
      - cryptography==44.0.2
      - cycler==0.12.1
      - databricks-sdk==0.44.1
      - debugpy==1.8.12
      - decorator==5.1.1
      - defusedxml==0.7.1
      - deprecated==1.2.18
      - docker==7.1.0
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - fastmri==0.3.0
      - filelock==3.17.0
      - flask==3.1.0
      - flatbuffers==25.1.21
      - fonttools==4.55.5
      - fqdn==1.5.1
      - frozenlist==1.5.0
      - fsspec==2023.10.0
      - gast==0.6.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-auth==2.38.0
      - google-pasta==0.2.0
      - graphene==3.4.3
      - graphql-core==3.2.6
      - graphql-relay==3.2.0
      - greenlet==3.1.1
      - grpcio==1.70.0
      - gunicorn==23.0.0
      - h11==0.14.0
      - h5py==3.12.1
      - httpcore==1.0.7
      - httpx==0.28.1
      - idna==3.10
      - imageio==2.37.0
      - importlib-metadata==8.5.0
      - ipykernel==6.29.5
      - ipython==8.31.0
      - ipywidgets==8.1.5
      - isodate==0.7.2
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.5
      - joblib==1.4.2
      - json5==0.10.0
      - jsonpickle==4.0.2
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.11.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.4
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - keras==3.8.0
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - libclang==18.1.1
      - lightning-utilities==0.11.9
      - mako==1.3.9
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.0
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mistune==3.1.0
      - ml-dtypes==0.3.2
      - mlflow==2.20.3
      - mlflow-skinny==2.20.3
      - mpmath==1.3.0
      - msal==1.31.1
      - msal-extensions==1.2.0
      - msrest==0.7.1
      - multidict==6.1.0
      - namex==0.0.8
      - nbclient==0.10.2
      - nbconvert==7.16.5
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - notebook==7.3.2
      - notebook-shim==0.2.4
      - numpy==1.26.4
      - oauthlib==3.2.2
      - opentelemetry-api==1.30.0
      - opentelemetry-sdk==1.30.0
      - opentelemetry-semantic-conventions==0.51b0
      - opt-einsum==3.4.0
      - optree==0.14.0
      - overrides==7.7.0
      - packaging==24.2
      - pandas==2.2.3
      - pandocfilters==1.5.1
      - parso==0.8.4
      - patchify==0.2.3
      - pexpect==4.9.0
      - pillow==11.1.0
      - platformdirs==4.3.6
      - portalocker==2.10.1
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.50
      - propcache==0.2.1
      - protobuf==4.25.5
      - psutil==6.1.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==19.0.1
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pycparser==2.22
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pygments==2.19.1
      - pyjwt==2.10.1
      - pyparsing==3.2.1
      - python-dateutil==2.9.0.post0
      - python-json-logger==3.2.1
      - pytorch-lightning==2.5.0.post0
      - pytz==2024.2
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - referencing==0.36.1
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.9.4
      - rpds-py==0.22.3
      - rsa==4.9
      - runstats==2.0.0
      - scikit-image==0.25.0
      - scikit-learn==1.6.1
      - scipy==1.15.1
      - seaborn==0.13.2
      - send2trash==1.8.3
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.6
      - sqlalchemy==2.0.38
      - sqlparse==0.5.3
      - stack-data==0.6.3
      - sympy==1.13.3
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.16.2
      - termcolor==2.5.0
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tifffile==2025.1.10
      - tinycss2==1.4.0
      - torch==2.2.2
      - torchaudio==2.2.2
      - torchmetrics==1.6.1
      - torchsummary==1.5.1
      - torchvision==0.17.2
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - types-python-dateutil==2.9.0.20241206
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - uri-template==1.3.0
      - urllib3==2.3.0
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.13
      - wrapt==1.17.2
      - yarl==1.18.3
      - zipp==3.21.0
